### ISSUE TITLE
Compteur d'actualités (+1) dans les onglets

### ISSUE THREAD

**Issue by lulu-nico** [Aqualizr/beta#1]
le chiffre des nouvelles news dans l'onglet comme pour les e mail serait une bonne chose
cdi le fait déjà
chose a reprendre

**Comment by Aqualizr** [comment]
Poste tt ca sur github ;)

**Comment by lulu-nico** [comment]
et bien je suis ou la ?

**Comment by Aqualizr** [comment]
Ceci n'est pas un bug, mais une idée d'amélioration. Il faut donc les poster dans https://github.com/Aqualizr/beta/pulls
Pour faciliter la lecture, et l'avancement de chaque idée, chaque bug, il faut créer un topic par idée avec un titre explicite.

**Comment by ysoudy** [comment]
Cette fonctionnalité est extremment gourmande en ressource, je vais réflchir à sa faisabilité

**Comment by lulu-nico** [comment]
peut être je ne mit connais passez assez sur ça mais c'est super pratique je trouve
