### ISSUE TITLE
Taille du mode icônes

### ISSUE THREAD

**Issue by cabou83** [Aqualizr/beta#10]
J'ai une petite suggestion pour le mode "icone" sur Aqualizr elles sont plus grosses que sur CDI donc sur un écran on voit moins de news sur Aqualizr que sur CDI. Perso je trouve la taille des icônes de CDI parfaites donc si tu peux la réduire sur Aqualizr ça serait top.
Je t'ai fait des captures d'écrans c'est plus parlant (768p là, mais en 1080p c'est encore plus parlant).

![capture aqualizr](https://cloud.githubusercontent.com/assets/10603880/5833749/97832e06-a156-11e4-9178-d3f7c997e58c.jpg)

![capture cdi](https://cloud.githubusercontent.com/assets/10603880/5833751/9b2dd092-a156-11e4-8f11-a51deb2eb549.jpg)

**Comment by lulu-nico** [comment]
pareil,pour l'interface miniature
ça reprend la façon d'on j'utilise l'appli mais c'es trop et donc pas assez de news

**Comment by lulu-nico** [comment]
en cas un mode petit moyen grand comme sur l'appli ?

**Comment by xenesys** [comment]
j'ai les etoiles a droite partiellement cachées par le cadre : 
en mode icone + mode miniature 
![capture d ecran 2015-01-22 18 41 49](https://cloud.githubusercontent.com/assets/10657107/5861057/57e9dc48-a266-11e4-9461-813cac703d28.png)

**Comment by lulu-nico** [comment]
pas chez moi
tu en encore des bug bizarre
lol

**Comment by xenesys** [comment]
a mon avis c'est firefox qui fait ca. C'est bien au moins ca permet de corriger :D :+1:

**Comment by ysoudy** [comment]
mode icone passé de 72px de haut à 48px
taille des etoiles corrigée sur firefox ;)

**Comment by ysoudy** [comment]
pouvez-vous confirmer la correction que je ferme le post ?

**Comment by cabou83** [comment]
Ouaip bonne taille maintenant merci ;)

**Comment by lulu-nico** [comment]
en miniature on change pas ?

**Comment by ysoudy** [comment]
Si je diminue la miniature va etre minuscule..

**Comment by lulu-nico** [comment]
si c'est un peu plus petit
mais comme sur l'appli la photo a la place de l'icone du site pas possible ?
on appel ça interface lulu-nico
lol
