### ISSUE TITLE
Options page principale - aqualizr.com/news/

### ISSUE THREAD

**Issue by xenesys** [Aqualizr/beta#13]
Le titre est pas clair j'ai pas trouvé mieux

Sinon mon idée est de regrouper les idées concernant la page des actus (ici : http://www.aqualizr.com/news/) (peu importe l'affichage) qui bien entendu ne seront surement pas toutes gardées au final ^^
exemples : (je les numerote histoire de les repertorier)

N°1 = Possibilité de cliquer sur les heures dans la barre verticale a droite et donc centrer les actu de l'heure choisie
N°2 = Pouvoir cliquer sur "derniere actu lue" pour rejoindre la derniere actu lue (c'est con à l'ecrire....)
N°3 = Si on clique sur l'icone d'un site cela affiche toutes les actu du site sur la page - on ajoute sous "tous les flux" le nom du site en question (en haut de la page) - il suffira alors de cliquer sur "tous les flux" pour revenir en arriere.
N°4 = (à suivre....)

N'hesitez pas à proposer :)

**Comment by ysoudy** [comment]
N°1/2 : oui, bonne idée, mais le problème, c'est s'il y a 5000 news entre les news actuelles, et la dernière news lue, ca va faire bcp à charger...

**Comment by ysoudy** [comment]
N°3 : pas évident... mais dans l'ajout d'un écran, j'ai imaginé la possibilité d'afficher toutes les news d'un seul site en particulier.

**Comment by xenesys** [comment]
Je dirais alors de garder au moins la N°1 elle me semble sur  le papier la moins dure à mettre en place.
On jette la N°2. non?

Ok pour la N°3.

**Comment by ysoudy** [comment]
Timeline abandonnée, bcp trop gourmand, et peu d'interet au final
Ca sera remplacé par autre chose ;)
