### ISSUE TITLE
Barre verticale/defilement sous firefox n'est pas prise en compte

### ISSUE THREAD

**Issue by xenesys** [Aqualizr/beta#14]
Speciale auto-dédicace pour ce sujet !! :D
Bug c'est un peu fort vu que c'est une beta mais j'aime ca ^^

N°1 = Si j'utilise la roulette de la souris pour me faire defiler la page des actu, la "position actuelle" suit mon mouvement. Si j'utilise la barre de defilement de firefox pour me deplacer plus de suivi. La "position actuelle" reste où elle est. Des que je rebouge avec la roulette je retourne à la derniere position de la ""position actuelle".

**Comment by ysoudy** [comment]
J'update le titre, un bug = un sujet, sinon, ca va etre dure de clore un demi-sujet à la fois ;)

Tu utilises quelle version de firefox que je regarde de mon coté ?

**Comment by xenesys** [comment]
Actuellement je suis sous FF35.0
Ok - je note. je decouvre github ^^

**Comment by ysoudy** [comment]
Quelle est la marque de ta souris ?

**Comment by xenesys** [comment]
c'est une logitech M500.

**Comment by ysoudy** [comment]
Ah.. .j'ai pe mal compris : tu dis que la molette fait bien changer la position
mais c'est si tu bouges la barre de défilement que ca bug ?

**Comment by ysoudy** [comment]
Corrigé ;) c'est bon pr toi ?

**Comment by xenesys** [comment]
Oui c'est bien la barre de defilement de firefox qui bug. a un moment j'ai eu un doute si tu avais bien compris mon explication. je vais tester et je reviens confirmer le fix.

**Comment by ysoudy** [comment]
N'oubliez pas de faire Ctrl + R pour recharger le cache du moteur javascript ;)

**Comment by xenesys** [comment]
A priori ca marche. Je me deplace et des que je relache la souris le curseur se positione correctment.
merci
