### ISSUE TITLE
Ajouter un zoom dans les paramètres d'affichage

### ISSUE THREAD

**Issue by xenesys** [Aqualizr/beta#15]
1 = Rapidement : ok sauf pour le mode apercu. Ca ressemble trop à mosaique et surtout y a pas plus d'info affichée par actu (texte je parle). Comme sur CDI. Il ne faudrait pas lui apporter un petit plus pour le differencier ?

2 = sur un 24" 1920x1200 ca fait un poil limite pour moi. Possible à l'avenir de changer la taille de la police ?

3 = Je ne sais pas si c'est vraiment un bug ou une fonction : pour chaque catégorie d'actu (sport/buzz/etc) il garde en memoire le mode d'affichage choisi. J'aurais pensé que si on choisit un mode, il s'applique pour tous. Là je peux faire du apercu pour buzz, liste pour monde, etc
C'est quoi le plus pratique / logique ?

**Comment by ysoudy** [comment]
1= je ne peux pas afficher + de texte... qu'il n'y en a. Il faut que je demande l'autorisation à tous les sites pour pouvoir afficher un résumé de leur blabla.

2= juste, c'est-à-dire ? trop petit, ou trop grand ?
Mais oui, on pourrait ajouter un zoom ;)

3= qd j'ajouterai la possibilité d'ajouter un écran, tu comprendras ;)

**Comment by xenesys** [comment]
1 = ok. je vois pas d'idée pour l'instant... a suivre.
2 = oui en mode liste ca fait un poil petit mais en mode icone c'est un peu plus grand donc mieux pour lire sur du 1920x1200 (je ne touche pas au zoom de firefox)
3 = ok j'attends alors ^^

**Comment by ysoudy** [comment]
le mode icon est passé de 72px à 48px de haut
toujours trop grand ?

**Comment by xenesys** [comment]
la taille du mode icone est bien (j'ai actualisé et pas constaté de difference depuis le changement.... je dois etre aveugle). c'est plus le mode liste qui est petit.

**Comment by ysoudy** [comment]
Affichage complétement revu.
Finalement, je m'adapte à chaque écran.
J'ai donc créé des templates poru chaque résolution : 2560, 1920, 1680, 1440, 1366, 1280, 1024...
