### ISSUE TITLE
Bug refresh en boucle

### ISSUE THREAD

**Issue by cabou83** [Aqualizr/beta#16]
J'ai un bug depuis ce matin, les news se rafraîchient sans cesse sans que je touche à quoi que ce soit et en plus ça fait ouvrir une fenêtre de texte. Et ça, en boucle...
Une petite image est plus parlante, je suis sous chrome...
![aqualizr](https://cloud.githubusercontent.com/assets/10603880/5886889/2df0c618-a3b5-11e4-9d6e-39ca19fec204.jpg)

**Comment by lulu-nico** [comment]
ton bug mets apparue en cliquant sur le logo du site en haut a gauche

**Comment by xenesys** [comment]
idem sur firefox en faisant un ctrl+r
aussi des que les petits carrés en haut pour un refresh la popup apparait "update"
je viens d'avoir une popup "next" quand je remonte le temps et que le site doit recharger les precedentes actus

**Comment by ysoudy** [comment]
Les joies de l'alpha test ;)
vous allez en voir des "toto" et trucs bizarres comme çà !

**Comment by xenesys** [comment]
probleme de nouveau present chez moi avec un "2" cette fois

**Comment by ysoudy** [comment]
Oui je debug ;)
