### ISSUE TITLE
Recherche

### ISSUE THREAD

**Issue by ysoudy** [Aqualizr/beta#18]
Un zone de recherche est apparue hier soir, et est opérationnel depuis cet aprem.
A l'avenir, il sera possible de créer un écran sur une recherche (pour créer un flux dynamique sur le mot clé de votre choix)

**Comment by xenesys** [comment]
Ca semble bien fonctionner sauf que :
avec le theme sombre on ne voit pas la loupe et le texte que l'on tape est noir sur fond gris.

**Comment by ysoudy** [comment]
ah oui, je n'ai pas encore mis les images pour l'interface sombre ;)
