### ISSUE TITLE
bug écran gris

### ISSUE THREAD

**Issue by lulu-nico** [Aqualizr/beta#20]
![image](https://cloud.githubusercontent.com/assets/10600450/5891995/2c27b966-a4b1-11e4-9df6-780f69136e5f.png)

**Comment by xenesys** [comment]
idem sur le theme sombre

**Comment by lulu-nico** [comment]
chez moi c'est revenue

**Comment by xenesys** [comment]
idem

**Comment by ysoudy** [comment]
periode de dev ;)
