### ISSUE TITLE
Les Pubs D'Aqualizr

### ISSUE THREAD

**Issue by xenesys** [Aqualizr/beta#23]
Juste pour remarquer plusieurs choses : 
- les pubs ont tendance a ralentir firefox des lors qu'elles se mettent a jour.
- lorsque l'on clique sur une actu, elles ont tendance à disparaitre quelques secondes avant de réapparaitre.
- c'est mieux qu'elles soient dans la colonne de droite vs qu'à gauche au milieu des options du site.
- elles n'apparaissent pas tout le temps - sur les 2 cadres a droite ca varie d'un chargement à l'autre de la page (meme apres un CTRL+R)

**Comment by ysoudy** [comment]
position de la pub revue.
Comme nous sommes en beta, tout peut sauter à chaque instant ;)
