### ISSUE TITLE
(Bug) Historique

### ISSUE THREAD

**Issue by xenesys** [Aqualizr/beta#24]
Visiblement l'historique fonctionne mais a quelques soucis de mémoire vu qu'il affiche chez moi des actu que je n'ai pas ouvert lol

**Comment by xenesys** [comment]
ca semble mieux fonctionner mais je fais remonter 2/3 trucs (je regroupe desolé)
- Petite correction a apporter : si on clique sur la meme actu dans la meme minute (j'ai fait un double clique par erreur) dans 'l'historique l'actu apparait autant de fois qu'on clique : faudra pas un peu limiter ?
- si on lit sans recharger la page l'heure de l'historique est figée jusqu'a ce qu'on raffraichisse la page

**Comment by xenesys** [comment]
j'en rajoute une : 
- si on clique a gauche de l'heure et de son point coloré : ca n'ouvre pas l'actu mais l'actu est rajoutée dans l'historique. c'est clair ?
- texte de l'histoirque est bien plus grand que le reste

**Comment by ysoudy** [comment]
Finalement, pas assez de place pour afficher l'historique... je ferai autrement
(genre un écran dédié à votre historique)
