### ISSUE TITLE
Nouveau rafraîchissement des news

### ISSUE THREAD

**Issue by lulu-nico** [Aqualizr/beta#25]
ça fait mal au yeux je suis le seul ?

**Comment by cabou83** [comment]
Oui c'est un peu plus agressif le faite qu'on voit les news disparaître et réapparaître d'un coup...
Comme disent les vieux : c'était mieux avant ! :D

**Comment by ysoudy** [comment]
oui, faut que je l'optimise... pas évident ;)

**Comment by ysoudy** [comment]
done, optimisé ;)
