### ISSUE TITLE
[RESOLU](Bug) PB page principale (bleue)

### ISSUE THREAD

**Issue by xenesys** [Aqualizr/beta#29]
l'image resume bien le souci : 
![capture d ecran 2015-02-10 09 17 07](https://cloud.githubusercontent.com/assets/10657107/6123667/aeadc4ec-b105-11e4-9ee7-e9386b731979.png)

**Comment by xenesys** [comment]
ce soir c'est pire lol
![capture d ecran 2015-02-10 17 55 44](https://cloud.githubusercontent.com/assets/10657107/6131702/14c0e320-b14e-11e4-816f-f644325f20dc.png)

**Comment by ysoudy** [comment]
Ben oui, c'est çà la beta ;)
