### ISSUE TITLE
(Questions) Futures evolutions

### ISSUE THREAD

**Issue by xenesys** [Aqualizr/beta#30]
Je crée ce sujet car j'ai quelques questions : 
- Actuellement le site a l'air de bien fonctionner dans l'ensemble, mais quelles sont les futures evolutions à venir ?
- Quelqu'un aurait une idée pour ameliorer et mieux organiser la remontée des infos (bug/idée/etc)? (j'ai l'impression qu'on fait remonter un peu tout en vrac alors que certains étaient dûs au developpement de la fonction)
- Ca serait peut etre mieux de créer une liste des evo à venir histoire de pouvoir les tester chacun (vu qu'on utilise un navigateur différent entre tous ca aidera a debugger)

**Comment by ysoudy** [comment]
- Je créerait des topics pour les évolutions
- Oui, c'est le bordel, mais heureusmeent, on peut clore les sujets ;)
- Qd on sera en mode "public", il y aura des versions, et des communications via twitter/facebook, etc...

Github reste donc un domaine très technique entre #teamdev et #old_members ;,)
