### ISSUE TITLE
Importation des paramètre de cdi

### ISSUE THREAD

**Issue by lulu-nico** [Aqualizr/beta#34]
Quand on lance aqualiz on nous demande soit de crée un compte ou de se connecter avec notre compte de cdi.
Comme par exemple 
Si on se connecte avec notre compte de cdi je pense qu'il serait bien que les paramètre commun entre les 2 site soit importé.
Comme par exemple les paramètre de nos thèmes d'actu  ou d'affichage ainsi que les news déjà lu et vu.
Il y a aussi les flux perso.
Un avis ?

**Comment by ysoudy** [comment]
Malheureusement, il y a trop de modifications pour que ce soit repris tel quel...
Et vu l'ambition, on va limiter sérieusement le nombre de flux persos pour les non-premium.
On ne peut donc pas les récuperer comme cela
