### ISSUE TITLE
ajouter un écran

### ISSUE THREAD

**Issue by lulu-nico** [Aqualizr/beta#36]
super interface mais ça ne m'a pas fait pensé a cliquer dessus pour y modifier le flux d'actue
du coup pourquoi pas changer le nom
"personnalisé le flux d'actu" me semble plus explicite

**Comment by lulu-nico** [comment]
j'y ai crée un écran il n’apparaît pas chez moi

**Comment by ysoudy** [comment]
quelles options as-tu mises pour cet écran ?
étais-tu connecté avec un compte ?

**Comment by lulu-nico** [comment]
je suis connecter sur mon compte oui

**Comment by ysoudy** [comment]
peux tu me dire exactement ce que tu as choisi dans les options d'ajout ?
que je vois ce qui ne marche pas

**Comment by lulu-nico** [comment]
capture Ecran plus simple non ?

**Comment by ysoudy** [comment]
oui, par mail si tu veux

2015-07-22 14:51 GMT+02:00 lulu-nico notifications@github.com:

**Comment by lulu-nico** [comment]
![image](https://cloud.githubusercontent.com/assets/10600450/8825790/f93fc93c-3081-11e5-891a-b960a2ef3cd3.png)
![image](https://cloud.githubusercontent.com/assets/10600450/8825803/09d6522a-3082-11e5-8098-43fa59ff5b1a.png)
![image](https://cloud.githubusercontent.com/assets/10600450/8825811/13b4cc7c-3082-11e5-9c06-d2c6dcdf7999.png)
![image](https://cloud.githubusercontent.com/assets/10600450/8825815/227e1c9a-3082-11e5-8d83-fd5302027792.png)

**Comment by ysoudy** [comment]
ok, je viens de corriger, j'ai réussi à l'ajouter chez moi

**Comment by lulu-nico** [comment]
pareil
si je ferme et re ouvre le site je retombe dessus ?

**Comment by ysoudy** [comment]
tu peux te déconnecter et reconnecter ?

2015-07-22 15:24 GMT+02:00 lulu-nico notifications@github.com:

**Comment by lulu-nico** [comment]
j'ai fermé la page et j'ai reouvert je retombe sur tous les flux
pouvoir fixer serait bien

**Comment by ysoudy** [comment]
fait Ctrl+R pour recharger le moteur javascript ;)
c'est corrigé ce bug, essaye d'ajouter de nouveaux écrans pr voir

**Comment by lulu-nico** [comment]
non je revient toujours sur tous les flux

**Comment by ysoudy** [comment]
oui effectivement, mais l'écran est bien ajouté ?
(c'est un mini upgrade que je dois faire pour aller directement au bon
écran)

**Comment by lulu-nico** [comment]
Ah oui le nouvelle écran c'est bon depuis un moment
mais j'aimerais pouvoir y rester a chaque lancement du site
ton option de mail a chaque news tu es fou
j'active ça mon tel sonne tous le temps

**Comment by ysoudy** [comment]
C'est une option ;) désactivée par défaut

2015-07-22 15:34 GMT+02:00 lulu-nico notifications@github.com:

**Comment by lulu-nico** [comment]
je suis plus sur le +1 comme cdi dans l'onglet c'est très utile
