### ISSUE TITLE
news lu

### ISSUE THREAD

**Issue by lulu-nico** [Aqualizr/beta#37]
on sait comment qu une news a été lue ?

**Comment by lulu-nico** [comment]
c'est un demi bug
la croix apparait mais pas en fermant la news
un peu plus tard
c'est dommage
on risque de re cliqué sur une news déjà lu

**Comment by lulu-nico** [comment]
enfin tant que je n'actualise pas le flux de news la croix n’apparaît pas
si j'actualise même de suite après ça arche

**Comment by ysoudy** [comment]
corrigé ;)

**Comment by lulu-nico** [comment]
![image](https://cloud.githubusercontent.com/assets/10600450/8927506/30096776-3518-11e5-8081-907a770df303.png)

a l'instant est sir 2 lignes

**Comment by ysoudy** [comment]
corrigé
