### ISSUE TITLE
bug ecran

### ISSUE THREAD

**Issue by lulu-nico** [Aqualizr/beta#38]
j'ai crée mon écran personnalisé
il marche comme j'aimerai
si je ferme mon navigateur on que j'eteins mon pc
en re ouvrant le navigateur je retombe directement dessus
par contre si je ferme juste l'onglet et que je le re ouvre je retombe sur tous les flux

**Comment by ysoudy** [comment]
chaque écran a un url spécifique (qui se termine par #nom_de_lecran)
si tu veux redemarrer depuis cet écran, alors tu dois enregistrer cet url comme favori
