### ISSUE TITLE
Sélection des flux publics

### ISSUE THREAD

**Issue by ysoudy** [Aqualizr/beta#4]
Fonctionnalité prévue en cours de développement :
Possibilité de (de)selectionner les flux publics

**Comment by xenesys** [comment]
heu je dois avoir le cerveau fatigué : tu veux dire publics comme les on/off sur le comptoir des sites "officiels" (pas ceux qu'on rajoute)?

Il sera possible de faire de meme avec les flux rss ou autre que l'on rajoute ?

**Comment by ysoudy** [comment]
Oui
Oui (voir https://github.com/Aqualizr/beta/issues/6)
;)
