### ISSUE TITLE
Problème ajout site Internet / Flux RSS

### ISSUE THREAD

**Issue by GotoRicK** [Aqualizr/beta#41]
Bonjour,
très très bien cette nouvelle version. Très complète, bravo pour tout le travail.
J'ai un petit bug.
Je veux ajouter (pour tester) un site Internet à mon suivi. Donc Ajouter écran > Ajout Site.
Je met comme site Internet : 
http://www.factornews.com.
Il trouve bien automatiquement l'URL du flux, c'est à dire : 
http://www.factornews.com/rss.xml.

Par contre, les actus qu'il affiche non simplement RIEN à voir avec le site Factornews. Je me retrouve avec des actualités en anglais et quand je clique sur le lien, le lien est erroné "adresse non valide".

**Comment by ysoudy** [comment]
Effectivement ;) les bugs de la beta.
Tu as été le 1er a créer une source perso, et l'ID technique de cette source correspondait à un ID de test de ma part. Bref, tu voyais les news de l'ancien site.

Corrigé depuis

**Comment by GotoRicK** [comment]
Ok maintenant je vois bien les bonnes actualités !
Par contre quand j'ouvre l'actu, ça m'envoi sur un lien en erreur, celui-ci : 
http:///

Que cela soit sur Chrome ou Firefox.

Autre deux petits points : 
- Lorsqu'on s'identifie et qu'on appuie sur "Login". Ca ne fait rien. Comme si le bouton ne fonctionnait pas. Pourtant lorsqu'on rafraichit à la main on voit que finalement ça a a bien marché et qu'on est effectivement logué.
- Il semblerait que lorsqu'on change de Nav ou PC, on perd l'information de la couleur Interface (day).
  Du coup par défaut on revient direct sur Night.

**Comment by ysoudy** [comment]
Corrigé aussi ;)

**Comment by GotoRicK** [comment]
Ben mince, chez moi ça marche toujours pas :/
Maintenant quand je clique sur le lien, ça me donne, sur Firefox : 
http://1/

Chrome: 
http://0.0.0.1

Du coup lien pas bon chez moi.

**Comment by ysoudy** [comment]
oops, et now ? ;)

**Comment by GotoRicK** [comment]
Au top ! Merci ! :)
