### ISSUE TITLE
Prise en charge symboles monétaires "€"

### ISSUE THREAD

**Issue by ClementSz** [Aqualizr/beta#42]
Bonjour,

dans le fil d'aujourd'hui une news avec dans le titre le symbole "€" n'arrive pas à l'afficher :

En copié-collé en inspectant l'élément : Il vole 100 000  dans les machines à café
Et donc sur le site de visu : Il vole 100 000  dans les machines à café

Il est donc certain que c'est le site qui ne prends pas en charge le symbole et non le titre qui a eu une coquille lors de sa publication.

D'ailleurs je me demande si la discussion "Affichage texte "oe"" par xenesys n'est pas véritablement un problème de prise en charge de symbole.

**Comment by ysoudy** [comment]
problème d'encodage de caractères, toujours très difficile à gérer ;)
en tout cas pour ce type de cas, c'est désormais corrigé
