### ISSUE TITLE
Rajout de couleurs d'interfaces

### ISSUE THREAD

**Issue by fun-evil** [Aqualizr/beta#43]
Bonjour :)

je sais que ce n'est pas primordial, mais je pensais que ca aurait été plus sympa de pouvoir choisir d'autres couleurs de thèmes pour l'interface plutot que les basiques Blanc ou noir qui sont assez terne et tristes.

Voila je ne sais pas si c'était prévu ou non, aussi je me permet de le suggérer

cordialement :+1: 

Alexis

**Comment by ysoudy** [comment]
Oui, bien sûr, on en ajoutera ;)

**Comment by fun-evil** [comment]
Ok merci :)

**Comment by Sn4444k3** [comment]
Un thème gris sur les cotés (le même gris que sur le comptoir de l'info la ou il y a la date et heure) et blanc au centre, un thème bi-gout en fait :D, ainsi que la même police que pour les news du comptoir ou une police qui ce li sans forcer, je trouve que la police actuel ce fond dans le blanc ça pique les yeux.

**Comment by ysoudy** [comment]
Interface grise ajoutée
