### ISSUE TITLE
Récupération de compte du Comptoir

### ISSUE THREAD

**Issue by Zebwest** [Aqualizr/beta#45]
Bonjour,

Alors voici donc le futur comptoir de l'info...
Je découvre...
A priori plutôt joli, c'est prometteur.

Pour aider à cette découverte, serait-il possible de récupérer les réglages d'actu faits dans nos comptes sur le Comptoir de l'info?
Donc de s'identifier directement sur Aqualizr avec les identifiants du comptoir, peut être?

Dans mon cas, je pourrais alors me servir un peu plus de cette nouvelle version pour la lecture des actus, afin de mieux contribuer au feedback.
Sinon, je tente tout de même, hein ,je participe tant que je peux.

Merci!

**Comment by Zebwest** [comment]
Bon, je me réponds tout seul:
Je vois que la question a déjà été posée, en découvrant github qui ne m'est pas familier...
Apparemment pas possible, tant pis!

**Comment by ysoudy** [comment]
Il y a certaines choses qui seront récupérables, comme les sources bloquées, et le choix de quelques thèmes.
Du coup, la solution serait de créer un écran "CDI" qui retrouverait vos préférences, vous pourrez ensuite le renommer, modifier, etc...

Ca irait comme solution ?

**Comment by Zebwest** [comment]
Oui, déjà, la récupérartion du choix des sources, c'est plutôt bien.
Cela permettrait de ne pas se refaire tout le tri des sources.

Sinon, une idée de ce qui serait réservé aux membres premium?

Petit détail:
Le choix d'affichage des news (miniature, liste...) n'est pas mémorisé et doit être fait à chaque fois.

Merci!

**Comment by ysoudy** [comment]
vu, je corrige çà ;)

**Comment by ysoudy** [comment]
done

**Comment by ysoudy** [comment]
Pour récuperer vos options (préférences d'actualités, sites bloqués), et vos sites persos allez sur cet url : http://www.aqualizr.com/restore/cdi/
