### ISSUE TITLE
Synchronisation appli et site

### ISSUE THREAD

**Issue by lulu-nico** [Aqualizr/beta#46]
il y a actuellement aucun synchro entre les 2

**Comment by ysoudy** [comment]
il n'y a surtout encore aucune application aqzr ;) donc difficile de synchroniser

**Comment by lulu-nico** [comment]
Avec l'appli cdi

**Comment by ysoudy** [comment]
le site aqzr n'est pas encore ouvert, juste en beta.
L'app ne devrait pas trop tarder ;)

2015-07-31 15:58 GMT+02:00 lulu-nico notifications@github.com:
