### ISSUE TITLE
Réglages non mémorisables

### ISSUE THREAD

**Issue by Zebwest** [Aqualizr/beta#47]
Hello,

Nouveau petit essai ce matin sur Aqualizr, je n'ai pas tenu longtemps...

Impossible de mémoriser des réglages de l'onglet Hi Tech, car le bouton "valider" ne répond pas (le bouton annuler fonctionne).
A signaler que l'onglet Hi Tech me met par défaut les news cinéma, séries, musique, et jeux vidéo, mais pas les news hi tech...

Et aussi, affichage de la page par dessus la colonne de droite:
![capture](https://cloud.githubusercontent.com/assets/13560814/9034247/70008480-39ce-11e5-9b0d-1a247b24abaf.JPG)

Retour sur CDI pour lire l'actu!

A bientôt!

Navigateur Firefox
Windows 10

**Comment by ysoudy** [comment]
Merci pour ces bugs ;)
corrigés !
