### ISSUE TITLE
Pb de couleurs

### ISSUE THREAD

**Issue by Zgouille** [Aqualizr/beta#48]
Bonjour,

Petit souci au niveau des couleurs de ligne.
![2015-08-07_115413](https://cloud.githubusercontent.com/assets/13692778/9133333/24b623d8-3cfb-11e5-8e47-801bbc3c2153.jpg)
Quand on séléctionne certaines lignes le texte n'est plus lisible.

Idem pour l'interface noire, même si c'est moins prononcé, il faut peut etre passer la police du texte en noir. Enfin ce n'est que mon avis.
![2015-08-07_115609](https://cloud.githubusercontent.com/assets/13692778/9133370/688428b2-3cfb-11e5-9229-59ec450352c9.jpg)

Sinon vraiment sympa l'interface.

Bon courage.

**Comment by ysoudy** [comment]
Qd tu dis "quand on sélectionne certaines lignes", tu veux dire quoi par "sélectionner" ?

**Comment by Zgouille** [comment]
Pardon, me suis mal exprimé, j'aurai du dire survol :)

**Comment by ysoudy** [comment]
Bien vu ;) problème corrigé
