### ISSUE TITLE
Pas de chargement des flux

### ISSUE THREAD

**Issue by iYo13** [Aqualizr/beta#51]
Je rencontre certains problèmes:
-alors que les flux "international" et "loisirs" se chargent sans difficultés; les écrans "tous les flux" et "hi-tech" ne sont pas disponibles.
-il n'est pas possible de changer le nom d'un flux rss ajouté manuellement (s'appelle RSS)
-j'ai voulu rajouter le flux rss de nextinpact (chez qui je ne suis pas abonné) l'onglet est cassé et ne peut pas être suprimé.

Au niveau des améliorations bienvenues j'aimerais voir apparaitre un affichage en liste avec miniature affichant une plus grande densité d'info au lieu d'une douzaine de titres uniquement.

Pour info j'utilise Firefox 40.0.3 et un écran UHD.
edit: au cas où la question se pose les modules d'extension ont été désactivés pour vérifier)

**Comment by ysoudy** [comment]
- Le bug d'affichage pour certains écrans a été corrigé. Merci pour ce retour.
- Quel est le site que tu veux changer ? le bouton "edit" ne fonctionne pas ?
- Je regarde pour NextInpact

**Comment by iYo13** [comment]
Le flux rss que j'ai ajouté est celui de cowcotland, qui s'est par ailleurs mis en place automatiquement.
Mais il s'appelle RSS est lorsque je change le titre dans la page de config de l'onglet (emplacement de saisie "nom de l'écran") de RSS à CCL les modifications ne sont pas appliquées.

**Comment by ysoudy** [comment]
Il y a eu du cafouillage...  si tu supprimes l'écran et que tu le recréé ? ca fonctionne ?

**Comment by ysoudy** [comment]
En tout cas, on peut désormais ajouter NextInpact (ils n'utilisent pas la balise meta pour indiquer le flux rss...tss..)

**Comment by iYo13** [comment]
Bon, la seule solution qui fonctionne pour l'instant c'est de recréer un écran en mettant le bon nom (pour nextinpact c'est par défaut, pour CCL il faut le changer à la main)

**Comment by ysoudy** [comment]
Du coup, tout est rentré dans l'ordre ?
