### ISSUE TITLE
Effet dans le chargement des nouvelles news

### ISSUE THREAD

**Issue by Nemasix** [Aqualizr/beta#52]
Bonjour,

je découvre moi aussi aujourd'hui cette béta. Tout d'abord, bravo pour le boulot :)

J'aurais une idée, ce serait d'afficher un effet lors du chargement des nouvelles news. Le chargement ajax des news est juste top, le seul problème c'est que visuellement, si ça fait 15 min que j'ai pas chargé, je ne vois plus où j'en suis. J'ai une dizaine de news qui apparaît (j'affiche les news en icônes) et c'est visuellement difficile de voir où j'en étais.

Comme je dis, c'est pas un bug, mais plus une suggestion :)

Merci encore pour le boulot fait et bon courage ;)

Goghvan

**Comment by ysoudy** [comment]
Normallement, les nouvelles news apparraissent avec un logo "NEW" rouge, si tu as choisis le mode APERCU, sinon l'heure est en rouge.

Mais sinon je vais réflechir à améliorer çà..

**Comment by Nemasix** [comment]
Ah oui l'heure est en rouge. J'ai le thème gris pour info, mais c'est vrai que je trouve ça pas trop visible (je l'avais pas vu xD ).

Après comme on dit, les goûts et les couleurs :P

**Comment by ysoudy** [comment]
tu utilises quel mode d'affichage ?

**Comment by Nemasix** [comment]
J'utilise le mode icône :)
