### ISSUE TITLE
Problème superposition

### ISSUE THREAD

**Issue by Zanzax** [Aqualizr/beta#53]
(Bonjour)

Sous W10 (15", 1366*768), FF40, j'ai eu à augmenter la taille du texte plusieurs fois pour le rendre lisible, avec l'effet que l'on peut voir sur l'impression d'écran. 

![sans titre](https://cloud.githubusercontent.com/assets/14058426/9583994/c353dc1c-500e-11e5-8421-bdcdaed02e06.png)

**Comment by Zanzax** [comment]
Qui plus est, la barre de navigation correspondant au menu de droite prend alors la main, et l'utilisation des flèches directionnelle du clavier fais défiler ce menu, et non les news.

**Comment by ysoudy** [comment]
Ah effectivement, si tu utilises le zoom logiciel, cela va tout casser ;)
tu dis qu'en zoom 100% le texte n'est pas assez lisible ? je vais l'augmenter

**Comment by ysoudy** [comment]
C'est bon pour toi la taille du texte désormais ?
