### ISSUE TITLE
Problème avec rss

### ISSUE THREAD

**Issue by NitroG42** [Aqualizr/beta#54]
Bonjour, j'ai un soucis avec le rss de ce site : http://www.hearthpwn.com/ (lien du rss http://www.hearthpwn.com/news.rss )
Ajouté dans aqualizer, nous avons les news du 1er septembre et du 31 aout, et pour les jours après, au lieu de ne rien avoir, il y a des news de site complétement différent : 
![screen](https://cloud.githubusercontent.com/assets/1549495/9598967/3926f646-5090-11e5-91bb-e07fe6f3c40d.png)
Chez un ami, toutes les news sont différentes, aucune ne provient de hearthpwn.

Sinon le site est super, félicitations !

**Comment by ysoudy** [comment]
Un problème de migration hier des sources CDI vers AQZR, c'est corrigé ;)
