### ISSUE TITLE
Impossible de rentrer des caractères spéciaux dans l'ajout de site

### ISSUE THREAD

**Issue by NitroG42** [Aqualizr/beta#55]
Certains sites ont des caractères spéciaux dans l'url : 
http://www.hearthhead.com/news&rss
Qui sont refusé du coup.

J'ai aussi ce flux qui ne fonctionne pas (mais là aucune idée) :
http://www.icy-veins.com/feed.atom

**Comment by ysoudy** [comment]
Ca devrait etre bon ;) tu peux les rajouter

**Comment by NitroG42** [comment]
Sur le premier http://www.hearthhead.com/news&rss devient http://www.hearthhead.com/news/news&rss et ca ne fonctionne pas, et pour le second, 
http://www.icy-veins.com/feed.atom ne met rien le champ url de flux, je l'ai ajouté quand même, et maintenant j'ai un écran "Test" qui ne reste même quand je le supprime, probablement car l'url est vide.
N'hésite pas si tu as besoin d'info ou de mon compte.

**Comment by ysoudy** [comment]
Attention, dans le premier champ, il faut mettre l'url du site, et non pas l'url du flux RSS !
Sinon, fait un CTRL+R pour bien recharger le moteur javascript

**Comment by NitroG42** [comment]
En mettant uniquement l'url du site ca laisse le champ vide (malgré un cmd maj r, je suis sous Mac et Firefox ), et ca fait ca sur les deux liens :
![capture d ecran 2015-09-01 a 14 01 14](https://cloud.githubusercontent.com/assets/1549495/9603598/00cdb844-50b2-11e5-8e97-f3fb6a0bb151.png)

**Comment by ysoudy** [comment]
Oui, Hearthhead.com n'indique pas le flux rss dans ses metas. AQUALIZR ne peut pas le deviner.. il faut donc le rentrer à la main !

Sur le site, recherche un lien vers "RSS", copie l'url, et colle le dans le champ RSS

**Comment by NitroG42** [comment]
C'est ce que j'avais essayé, je viens de comprendre il faut : 
- Rentrer l'url du site (car l'url du flux avec new&rss bloque toujours)
- Attendre la recherche pour avoir le champ rss
- ensuite dans le champ rss mettre la bonne url

Par contre j'ai toujours le soucis d'avoir ajouter un écran avec l'url RSS vide, et je ne peux plus le supprimer. Je crée une issue séparée ?

**Comment by ysoudy** [comment]
il va disparaitre tout seul à la prochaine correction ;)

**Comment by NitroG42** [comment]
Ca marche, merci beaucoup !
