### ISSUE TITLE
Bug affichage page de réglage d'un "écran"

### ISSUE THREAD

**Issue by Zebwest** [Aqualizr/beta#56]
Hello,

Ca faisait un petit moment que je n'avait pas essayé Aqualizr...
Je constate des améliorations et le fait que ce soit désormais plus fonctionnel.
Je vais donc l'utiliser, le confort d'utilisation étant bon, à priori.
La fonctionnalité des écrans" est celle qui me séduit le plus (personnalisation poussée, et possibilité des mémoriser les réglages de plusieurs personnes sur un même compte, ce que j'avais proposé pour CDI, sans succès).
Bon travail effectué!

Bon, à signaler, un petit bug d'affichage dans la page de réglages des écrans:
<a href="http://zupimages.net/viewer.php?id=15/36/m7vx.jpg"><img src="http://zupimages.net/up/15/36/m7vx.jpg" alt="" /></a>

Sinon, une question par rapport au premium:
Je vois que l'option est active, donc ce sera ok pour moi.
Mais le premium Aqualizr active-t-il aussi celui de CDI (mon premium CDI se finit bientôt)?
Si non, que dois-je choisir? Aqualizr semble bien lancé... plutôt mieux placé pour un avenir plus ou moins proche...

Merci!

Edit:
Une aberration trouvée!
Dans l'écran CDI, qui résulte de la récupération du compte CDI, le Comptoir du Hardware est absent (je confirme sa présence dans mes réglages CDI)!
M'enfin, voyons!

Et petit commentaire sur l'actualisation des news:
Je trouve cette actualisation un peu trop sensible quand on remonte dans la page, ce qui enlève le marquage "news non lues" un peu vite.
Je ne sais pas si je ne préférais pas le bouton dédié dans CDI...
Question d'habitude, sans doute, sur le principe c'est pourtant une bonne idée, comme sur l'appli.

**Comment by Zebwest** [comment]
Plus embêtant, toujours à propos du marquage en rouge des news non lues (indispensable).
Ce marquage disparaît lorsqu'on descend vers les news plus anciennes (et pas forcément lues) et qu'une actualisation est faite au niveau des bandeaux (pub? pas affichée pour moi, adblock désactivé).

Au fait, je ne sais pas si c'est utile:
Navigateur: FF 40
Windows 10

**Comment by Zebwest** [comment]
Nouveau bug:
Certaines news s'affichent comme lues alors que je déroule la liste, mais je ne les ai pas lues...

**Comment by ysoudy** [comment]
Hello ;)
Bugs corrigées : superposition, et news non lues qui passent en lues lorsqu'on scroll vers le bas

Pour répondre à ta question, oui le premium sur CDI sera prolongé sur AQUALIZR ;) et vice versa.
D'ailleurs, si tu veux etre le premier à betatester le mode premium sur AQZR, dis moi qd tu le fais, que je regarde dans mes mails ! ;)

**Comment by Zebwest** [comment]
Salut,

Bug news non lues toujours présent lorsque je scrolle vers le bas...
En fait les news du haut restent en rouge, mais celle d'en dessous sont en "lues" (alors que non, justement, je scrolle vers le bas pour retrouver les dernières news lues.

D'ailleurs, serait il possible d'arriver directement aux dernières news lues lorsqu'on arrive sur la liste (comme CDI), plutôt que sur les dernières news en date?

OK pour le premium, je le fait sur AQUALIZR, si cela fonctionne bien aussi pour CDI et l'app Android.
Paiement tout juste fait!

Merci!

**Comment by ysoudy** [comment]
ah c'est toi ;) bon bah go !
Je vais regarder pour ce bug
