### ISSUE TITLE
Afficher les écrans en parallèle

### ISSUE THREAD

**Issue by Darkwa** [Aqualizr/beta#57]
Serait-il possible, un peu à l'image de TweetDeck pour twitter, d'afficher plusieurs colonnes cote à cote afin de pouvoir jeter un oeil à plusieurs files d'actualités en même temps?
Image d'illustration : http://cdn1.tnwcdn.com/wp-content/blogs.dir/1/files/2013/06/Screen-Shot-2013-06-05-at-16.34.35.png

**Comment by ysoudy** [comment]
Grosse évolution à prévoir... Je mets de côté pour l'idée
