### ISSUE TITLE
Tous les flux bloqués hier à 13h

### ISSUE THREAD

**Issue by NitroG42** [Aqualizr/beta#58]
Sur la home depuis ce matin, les news affichés sont uniquement celle depuis hier 13h.
Ca marche quand je me déconnecte, mais sur mon compte non.
Les autres écrans fonctionnent.
(J'ai testé sur deux ordis différents, même soucis).

**Comment by ysoudy** [comment]
Ce bug a été corrigé dans la journée. Il s'agissait d'une news corrompue

**Comment by NitroG42** [comment]
Malheureusement, je l'ai toujours... Je suis repassé sur le comptoir de l'info en attendant, mais voici ma page d'accueil :
![capture d ecran 2015-10-06 a 16 55 02](https://cloud.githubusercontent.com/assets/1549495/10312316/08be72e6-6c4b-11e5-8117-cd32533d2da9.png)
Avec Firefox 41 sur Mac OS X
(Ce sont des news qui date du 19 septembre)

**Comment by ysoudy** [comment]
Woooo bien vu ;)
gros bug !!!! corrigé ;)
je vais tenter de récuperer l'historique
