### ISSUE TITLE
Affichage bloqué au dialog lors du changement de mot de passe

### ISSUE THREAD

**Issue by erazordoraemon** [Aqualizr/beta#59]
Après avoir entré son email pour changer son mot de passe le bouton ok ne fonctionne pas et renvoi cette erreur dans la console :

```
Uncaught SyntaxError: Unexpected identifierreq.onreadystatechange @ aqzr.js:84
aqzr.js:83 select count(*) from usr_accounts where usertype="register" and email="stevens.mauge@yahoo.fr" and connect not in ("facebook","google")Array
(
    [0] => 0
)
reset_error();
```

Je suis sous cette Version 45.0.2454.101 Ubuntu 14.04 (64-bit) de Chromium

**Comment by ysoudy** [comment]
Peux tu réessayer ?

**Comment by erazordoraemon** [comment]
Lorsque je clique sur Identification il ne se passe rien.
j'ai l'impression que ça fait un console.log

**Comment by ysoudy** [comment]
Je ne trouve aucun compte avec ton email..

Quel est ton identifiant ?
Tu t'étais inscrit sur CDI ?
ou sur AQUALIZR, et dans ce cas, via l'inscription classique, Google+ ou Facebook ?

**Comment by erazordoraemon** [comment]
L'email pour mon compte est erazor91@hotmail.fr
Sinon j'ai mon compte depuis que je suis inscrit sur le comptoir du hardware.

**Comment by erazordoraemon** [comment]
Sinon j'ai réussi à afficher le modal pour réinitialiser son mot de passe. Et je suis toujours bloqué sur le modal un fois appuyé sur ok.

```
reset_sent();
VM782:1 Uncaught ReferenceError: reset_sent is not defined(anonymous function) @ VM782:1req.onreadystatechange @ aqzr.js:84
```

Par contre je confirme que j'ai bien reçu le nouveau mot de passe.
C'est juste que j'ai aucune confirmation à part dans la console js du navigateur.

**Comment by ysoudy** [comment]
Alors tu devrais recevoir un email avec ton nouveau pass
Par contre, je vais corriger ce bug d'affichage

**Comment by erazordoraemon** [comment]
Non, contrairement au comptoir où je reçois directement un nouveau mot de passe, j'ai reçu un lien pour le réinitialiser.
Ce que j'ai fait.
Sauf que j'arrive pas à me connecter avec le nouveau mot de passe.

**Comment by ysoudy** [comment]
Surement parcque tu entres ton email au lieu de ton identifiant ;)
j'ai laissé la possibilité de mettre les 2 désormais
réessaye

**Comment by erazordoraemon** [comment]
J'ai essayé avec mon identifiant et mon email et ça fonctionne avec aucun des deux.
Sinon je viens de tester le formulaire. On est bien notifié pour l'envoi de l'email
