### ISSUE TITLE
Fonction pour bannir des sites (ex: Gizmodo, comptoir du geek)

### ISSUE THREAD

**Issue by erazordoraemon** [Aqualizr/beta#60]
Bonjour, 
Utilisant pas mal de temps le site et l'app du comptoir de l'info j'ai toujours été frustré par le fait qu'on ne puisse pas bannir des sites à clics comme ceux cités au dessus ou par exemple allociné qui est bourré de pub envahissantes et qui ne fonctionne pas sur mobile. 
ça pollue vraiment l'utilisation et c'est très dommage.

Merci.

**Comment by ysoudy** [comment]
Sur AQUALIZR.com, Dans tous les écrans (sauf celui qui les inclut tous) tu peux sélectionner les sources que tu veux (et donc enlever celles que tu ne veux pas ;)

**Comment by erazordoraemon** [comment]
Effectivement je n'avais pas poussé assez loin dans les paramètres, c'est un peu câché.
C'est parfait pour le coup. Vivement l'application mobile.
