### ISSUE TITLE
D'ou vient le nom du site ?

### ISSUE THREAD

**Issue by lulu-nico** [Aqualizr/beta#7]
Tous est dans le titre

**Comment by ysoudy** [comment]
Le Comptoir de l'Info v2 a pour objectif de s'ouvrir à de nouvelles langues. Il a donc fallu trouver une version internationale (les deux "marques" coexisteront en France).

Pour la petite histoire, AQUALIZR est un mix entre : aqua et equalizer
Equalizer : sert à ajuster les fréquences sonores (basses / aigues) pour la musique. L'interface utilisée pour choisir ses thèmes ressemble fortement à un équaliseur.
Aqua : l'information est comme une goutte d'eau, lorsqu'on la publie, elle fait des vagues/ondes à la surface de l’eau.

**Comment by lulu-nico** [comment]
ok pourquoi pas

**Comment by xenesys** [comment]
ah bien trouvé je trouve belle imagination ^^
faudra quand meme bien communiquer sur le but du site sinon ca risque de tromper un peu les gens.

**Comment by lulu-nico** [comment]
un nouveau sur le forum mais comment a t il été invité ?
lol

**Comment by xenesys** [comment]
y en a qu'un qui peut inviter faut se plaindre à lui :D

**Comment by lulu-nico** [comment]
Non a moi il t'avait oublié je lui ai rappellé de t'inviter
mais il faut pas le dire
lol

**Comment by ysoudy** [comment]
En fait j'ai invité lulunico sur ce forum en premier pour qu'il arrete de
me spammer : ya des fois mon tel fait bipbipbipbip toutes les minutes ;)

**Comment by lulu-nico** [comment]
je dois le prendre comment ?
lol

**Comment by xenesys** [comment]
Aah bah c'est joli de m'avoir oublié XD
Merci Lulu d'avoir pensé a moi lol

Lulu le spammer ? ^^'''
