### ISSUE TITLE
News au même horaire

### ISSUE THREAD

**Issue by lulu-nico** [Aqualizr/beta#8]
j'ai plein de news qui apparaisse a la même heure
les news non lu passe de suite de rouge a normal
difficile de voir se qu'on a lu ou non
news publié dans la journée qui revient plus tard dans la journée aussi
c'est un bug ou une nouveauté ?

**Comment by cabou83** [comment]
Pareil pour ma part

**Comment by ysoudy** [comment]
Pour les thèmes où vous avez choisi 100% en quantité d'information, les news sont publiées en temps réel
Pour les thèmes où vous avez choisi de 25 à 75% en quantité, il faut donc un certain temps pour identifier les news essentielles parmi toutes les news (pour ne vous proposer que les plus intéressantes). Cette analyse est faite toutes les 30min (11h30, 12h00, 12h30, ...) c'est pourquoi toutes les 30min, apparaissent les news qui ont été identifiées comme essentielles.

Sur CDI, j'avais choisi d'afficher l'heure véritable des news, mais...
Imaginez que : 
- vous avez choisi 50% des news sport
- il est 11h38
- une news sport est publiée par un site à 11h25
  => cette news ne sera donc visible qu'à partir de 12h00 (le temps de vérifier si c'est bien une news intéressante)
  Bref, à 11h59 dans votre flux, cette news ne sera pas visible, mais à 12h00, cette news de 11h25 apparaitra d'un seul coup... en dessous de toutes les news publiées depuis 11h25.

C'est compliqué à expliquer/comprendre, mais je reflechis au meilleur moyen de mixer des flux en temps réel, avec des flux différés... c'est pas évident !
Je suis preneur de toute bonne idée ;)

**Comment by lulu-nico** [comment]
je n’étais pas en temps réel je viens de comprendre comment on fait
il faudra quand même pouvoir éliminer les site qu'on ne veut pas comme sur cdi

**Comment by ysoudy** [comment]
regarde les fonctionnalités futures ;) c'est bien évidemment prévu

**Comment by lulu-nico** [comment]
il serait d’ailleurs bon de faire comme sur l'appli mobile de mettre quelque phrase ou mots d'explication pour des option dure a comprendre

**Comment by ysoudy** [comment]
Je vais réflechir à une représentation plus facile à comprendre... c'est pas normal d'avoir à expliquer une interface.
Je revois donc la copie sur le mix entre un flux en temps réel, et un flux différé

**Comment by lulu-nico** [comment]
avec les % on ne pense pas temps réel ou différé
on pense qu'on aura que x% des news de la categorie

**Comment by lulu-nico** [comment]
j'ai mis en temps réel je n'ai plus de news qui apparaissent d'un coup
par contre les nouvelle news reste rouge que 1s c'est un problème on ne sait plus les news qu on a vu ou pas
comment je sais si j'ai lu ou non une news ?

**Comment by ysoudy** [comment]
oui, c'est un bug çà ;)

**Comment by lulu-nico** [comment]
ça ne marche pas juste en mode liste apparement

**Comment by xenesys** [comment]
"mixer des flux en temps réel, avec des flux différés... " mettre une petite icone de :hourglass: d'horloge a coté des actu différées ?

sinon pour le coup des couleurs apres lecture (si j'ai bien tout compris votre discussion) ca semble pas marcher chez moi peu importe le mode d'affichage. j'ouvre des actus et je ne vois aucun changement. j'ai tout compris ??....

**Comment by lulu-nico** [comment]
sur cdi tu actualise les nouvelles news reste rouge jusqu’à ce que tu réactualise a nouveau
c'est utile tu sais les news que tu n'a pas regarder
après tu clic si ça t’intéresse ou pas
la ce truc ne marche pas

**Comment by xenesys** [comment]
depuis ce matin les nouvelles actu apparaissent en rouge mais dans la seconde qui suit elles repassent en gris.

**Comment by lulu-nico** [comment]
on aimerait que ça reste rouge jusqu’à se que qu'on reactualise

**Comment by ysoudy** [comment]
oui bien sur ;) c'est un bug, en cours de dev

**Comment by lulu-nico** [comment]
je me doute j'insiste parce que plus haut xenesys a dit ne pas comprendre
j’espère que cette fois c'est bon
par contre bon point pour ton nouveau site certain site s'affiche maintenant chez moi mieux qu'avant
la synchro a l'aire d’être plus rapide aussi comme sur l'appli mobile

**Comment by xenesys** [comment]
C'est bon maintenant. j'ai compris ^^
en fait c'est comme sur CDI

**Comment by lulu-nico** [comment]
oui voila enfin on aimerait que ça soit comme sur cdi

**Comment by xenesys** [comment]
Je sais pas si je dois faire 2 sujets pour ca :
- juste pour dire qu'il n'y a plus l'icone dans la barre de temps a droite de "derniere actu lue" elle n'apparait plus chez moi.
- Aussi quand je navigue avec la molette si je fais rouler pour remonter en haut quasi obligé que la mise a jour des actu se lance. Possible de bloquer en haut et si on relance une montée a ce moment on lance la mise a jour des actu ?
