### ISSUE TITLE
Flux Anglais

### ISSUE THREAD

**Issue by cabou83** [Aqualizr/beta#9]
Bon déjà je comprend pas l'interface de "idées et suggestions" donc je publie là dans "bug", mais c’est bien une suggestion que je veux faire.

C'est prévu de rajouter des sites en anglais (de base) ou pas ? Des sites comme comme Fudzilla, Videocardz ou wccftech...
Je pense que ça pourrait être un plus vu que maintenant Aqualizr vise l’international. Mais ça doit rester une option activable via la personnalisation des flux qu'on souhaite voir. Du genre si le mec met 100% en Hardware faudrait qu'il y ait à coté une case a cocher du type "voulez vous avoir accès au news de hardware des sites étrangers ?".

**Comment by ysoudy** [comment]
Pour le moment, il n'y a que des sources FR, mais le service étant international, nous allons ajouter des flux des principaux pays.
Par défaut, on ne verra que les flux de son propre pays, mais il y aura la possibilité de selectionner ceux des autres

**Comment by cabou83** [comment]
Ben parfait ! :)
